### PR TITLE
RNN Forecaster

### PR DESCRIPTION
**Pull request by pedrofale**
This branch extends the original project to include a new classifier: the Recurrent Neural Network. Following the latest update to the Time Series Forecasting package (version 1.0.22), this type of network can now be used to perform forecasting on Weka.

For information on how to use the Time Series Forecasting package, see [this page](http://wiki.pentaho.com/display/DATAMINING/Time+Series+Analysis+and+Forecasting+with+Weka).

When using the RNN forecaster, LSTM and RNNOutput layers must be used. Currently no LSTM/Dense/Conv layer mixing is supported.

### CODE REVIEW

**Comment by pedrofale** [comment]
Here you go, Chris. It's all working now. :-)

**Comment by christopher-beckham** [comment]
Thanks! That was very nice of you to make it compatible with my version. Just a question, do you have a unit test class for your code? Cheers

**Comment by pedrofale** [comment]
I just added a very simple test now. I'll surely do more in the future

**Comment by christopher-beckham** [comment]
Thank you, I'll have another look soon.

**Comment by christopher-beckham** [comment]
Cool, it's merged now. I had to retroactively remove the lib folder though (and build), as build artifacts shouldn't be included with the commits. Cheers :)

**Comment by pedrofale** [comment]
Right! Sorry about that - this project was actually my first using git. Glad it's merged now! Thanks Chris. BTW, I'll send you a retrospective e-mail sometime next week regarding the end of my internship. Cheers!

**Pull request merged**
